# ---
# - name: 1.1. Creating LibVirt Network Bridge for the OpenShift Cluster
#   community.libvirt.virt_net:
#     state: present
#     autostart: true
#     name: "{{ create_kvm_infra_net_bridge_name }}"
#     xml: "{{ lookup('template', 'network_bridge.j2') }}"

# # DEBUG: Maybe it would be better to move this task to the deploy role
# - name: 1.2. Activating LibVirt Network Bridge for the OpenShift Cluster
#   community.libvirt.virt_net:
#     state: active
#     name: "{{ create_kvm_infra_net_bridge_name }}"
# ...
