---
kvm_server:
  hosts:
    kvm.beri.lab:
  vars:
  children:

vm_hosts:
  hosts:
    bastion.ocp4.beri.lab:
    master01.ocp4.beri.lab:
    master02.ocp4.beri.lab:
    master03.ocp4.beri.lab:
    worker01.ocp4.beri.lab:
    worker02.ocp4.beri.lab:
    worker03.ocp4.beri.lab:
  vars:
  children:

tunneled_remote_hosts:
  hosts:
  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p staging-tunnel-jumphost"' # Only needed for ssh connections -> delegate_to: host
    # ansible_ssh_private_key_file: ~/.ssh/mykey1.pem
  children:
...
